/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OneVsOneBlackRoom } from "./OneVsOneBlackRoom";
export * as factories from "./factories";
export { OneVsOneBlackRoom__factory } from "./factories/OneVsOneBlackRoom__factory";
